front:
  server:
    url: http://localhost:8081
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: ${DATABASE_URL}
    username : ${DATABASE_USERNAME}
    password : ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  header: Authorization
  secret:
    key: ${JWT_SECRET_KEY}
  expiration_time: 86400
logging:
  level:
    org.springframework.security: debug
